{
 "title": "Infrastructure Sanity Check",
 "tags": [ "provisioned" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus Datasource", "query": "prometheus" },
   { "name": "DS_LOKI", "label": "Loki Datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node CPU Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "avg by (alias) (\n  irate(node_cpu_seconds_total{job=\"node_monitor\", mode!=\"idle\"}[5m])\n) * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Disk Usage Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{job=\"node_monitor\", mountpoint=\"/\"} - node_filesystem_free_bytes{job=\"node_monitor\", mountpoint=\"/\"}) / node_filesystem_size_bytes{job=\"node_monitor\", mountpoint=\"/\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node Ram Usage Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job=\"node_monitor\"} - node_memory_MemAvailable_bytes{job=\"node_monitor\"}) / node_memory_MemTotal_bytes{job=\"node_monitor\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Node CPU Usage Monitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - avg by (alias) (irate(node_cpu_seconds_total{job=\"node_monitor\", mode=\"idle\"}[5m]))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Citra Kuliner Redis Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_memory_used_bytes{job=\"redis_monitor\"} / redis_memory_max_bytes{job=\"redis_monitor\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Citra Kuliner Mysql Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"citra_kuliner_app-mariadb-1\"} / container_spec_memory_limit_bytes{name=\"citra_kuliner_app-mariadb-1\"} * 100",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Citra Kuliner Backend Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name=\"citra_kuliner_app-laravel-1\"} * 100) / container_spec_memory_limit_bytes{name=\"citra_kuliner_app-laravel-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Citra Kuliner Load Balancer Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(container_memory_usage_bytes{name=\"citra_kuliner_app-load_balancer-1\"} * 100) / container_spec_memory_limit_bytes{name=\"citra_kuliner_app-load_balancer-1\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  { "title": "Bandwith Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Mariadb Inbount / Outbount Rates (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_bytes_received{job=\"mariadb_monitor\"}[5m]) / 1000000",
     "legendFormat": "Inbound"
    },
    {
     "expr": "irate(mysql_global_status_bytes_sent{job=\"mariadb_monitor\"}[5m]) / 1000000",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Mariadb Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "query" } },
   "targets": [
    {
     "expr": "irate(mysql_global_status_queries{job=\"mariadb_monitor\"}[5m])",
     "legendFormat": "Queries Per Second"
    },
    {
     "expr": "irate(mysql_global_status_slow_queries{job=\"mariadb_monitor\"}[5m])",
     "legendFormat": "Slow Queries"
    }
   ]
  },
  {
   "title": "Mariadb Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 35 },
   "targets": [
    {
     "expr": "mysql_global_status_threads_connected{job=\"mariadb_monitor\"}",
     "legendFormat": "Current Threads"
    },
    {
     "expr": "mysql_global_variables_max_connections{job=\"mariadb_monitor\"}",
     "legendFormat": "Max Threads"
    }
   ]
  },
  {
   "title": "Redis Inbount / Outbount Rates (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "irate(redis_net_input_bytes_total{job=\"redis_monitor\"}[5m]) / 1000000",
     "legendFormat": "Inbound"
    },
    {
     "expr": "irate(redis_net_output_bytes_total{job=\"redis_monitor\"}[5m]) / 1000000",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Redis Disk I/O (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_aof_last_rewrite_duration_sec{job=\"redis_monitor\"}",
     "legendFormat": "Last Rewrite Duration Second"
    },
    {
     "expr": "redis_rdb_last_bgsave_duration_sec{job=\"redis_monitor\"}",
     "legendFormat": "BG Save Duration Second"
    }
   ]
  },
  {
   "title": "Redis Disk Error (Mb)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 43 },
   "targets": [
    { "expr": "redis_aof_last_write_status", "legendFormat": "Write Status" }
   ]
  },
  {
   "title": "Citra Kuliner Redis Connect",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "redis_connected_clients{job=\"redis_monitor\"}"
    }
   ]
  },
  { "title": "Prometheus Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Prometheus: Connected Targets (up)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job) (up{job=~\".*_monitor\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Cpu Usage / Container Client",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name, alias) (rate(container_cpu_usage_seconds_total{name!=\"\", alias=\"VPS-Client-Prod\"}[5m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Cpu Usage / Container Main",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(name, alias) (rate(container_cpu_usage_seconds_total{name!=\"\", alias=\"VPS-Master-Self\"}[5m])) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sevice Memory Working Set Percentage / Total Memory Main VPS",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name!=\"\",alias=\"VPS-Master-Self\"} / on(alias) group_left () (node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Total",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(alias, name) (container_memory_usage_bytes{alias=\"VPS-Master-Self\", name=~\"citra_kuliner.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sevice Memory Working Set Percentage / Total Memory Client VPS",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{name!=\"\",alias=\"VPS-Client-Prod\"} / on(alias) group_left () (node_memory_MemTotal_bytes) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory Usage Total",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(alias, name) (container_memory_usage_bytes{alias=\"VPS-Client-Prod\", name=~\"citra_kuliner.*\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Load Balancer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Nginx Up",
   "type": "stat",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{job=\"nginx_monitor\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Nginx Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 3, "y": 85 },
   "targets": [
    {
     "expr": "nginx_connections_active{job=\"nginx_monitor\"}",
     "legendFormat": "Aktif {{job}} {{alias}}"
    }
   ]
  },
  {
   "title": "Nginx Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 85 },
   "targets": [
    {
     "expr": "nginx_connections_reading{job=\"nginx_monitor\"}",
     "legendFormat": "reading - {{alias}}"
    },
    {
     "expr": "nginx_connections_writing{job=\"nginx_monitor\"}",
     "legendFormat": "writing  - {{alias}}"
    },
    {
     "expr": "nginx_connections_waiting{job=\"nginx_monitor\"}",
     "legendFormat": "Waiting - {{alias}}"
    }
   ]
  },
  {
   "title": "Traffic Intensity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{job=\"nginx_monitor\"}[1m])",
     "legendFormat": "Active - {{alias}}"
    }
   ]
  },
  {
   "title": "Citra Kuliner Backend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"citra_kuliner_app-load_balancer-1\"} | json | host = \"api.citrakuliner.test\" | line_format \"IP: {{.remote_addr}} | Status: {{.status}} | Up_Status: {{.upstream_status}} | Req_Time: {{.request_time}}s | Up_Time: {{.upstream_response_time}}s | Ref: {{.http_referrer}}\""
    }
   ]
  },
  {
   "title": "Citra Kuliner S3",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"citra_kuliner_app-load_balancer-1\"} | json | host = \"s3.citrakuliner.test\" | line_format \"IP: {{.remote_addr}} | Status: {{.status}} | Up_Status: {{.upstream_status}} | Req_Time: {{.request_time}}s | Up_Time: {{.upstream_response_time}}s | Ref: {{.http_referrer}}\""
    }
   ]
  },
  {
   "title": "Citra Kuliner Frontend",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"citra_kuliner_app-load_balancer-1\"} | json | host = `citrakuliner.test` | line_format `IP: {{.remote_addr}} | Status: {{.status}} | Up_Status: {{.upstream_status}} | Req_Time: {{.request_time}}s | Up_Time: {{.upstream_response_time}}s | Ref: {{.http_referrer}}`"
    }
   ]
  },
  {
   "title": "Citra Kuliner Minio",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"citra_kuliner_app-load_balancer-1\"} | json | host = \"minio.citrakuliner.test\" | line_format \"IP: {{.remote_addr}} | Status: {{.status}} | Up_Status: {{.upstream_status}} | Req_Time: {{.request_time}}s | Up_Time: {{.upstream_response_time}}s | Ref: {{.http_referrer}}\""
    }
   ]
  },
  { "title": "Container", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Citra Kuliner Logging File",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_ingester_chunk_stored_bytes_total",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Citra Kuliner Logging File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(name) (rate(container_fs_writes_bytes_total{name!=\"\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Citra Kuliner Logging File",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Citra Kuliner Laravel App",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"citra_kuliner_app-laravel-1\"} |= ``"
    }
   ]
  },
  {
   "title": "Citra Kuliner Redis",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"citra_kuliner_app-redis-1\"} |= ``"
    }
   ]
  },
  {
   "title": "Citra Kuliner Mariadb",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"citra_kuliner_app-mariadb-1\"} |= ``"
    }
   ]
  }
 ]
}