# 1. DEFINISI FORMAT LOG JSON (Sangat penting untuk Loki)
log_format json_analytics escape=json '{'
    '"time_local":"$time_local",'
    '"remote_addr":"$remote_addr",'
    '"host":"$host",'
    '"request":"$request",'
    '"status":"$status",'
    '"body_bytes_sent":"$body_bytes_sent",'
    '"request_time":"$request_time",'
    '"upstream_addr":"$upstream_addr",'        # Mengetahui container mana yang memproses
    '"upstream_status":"$upstream_status",'    # Status dari container tujuan
    '"upstream_response_time":"$upstream_response_time",'
    '"http_referrer":"$http_referer",'
    '"http_user_agent":"$http_user_agent"'
'}';

# 2. RESOLVER (Internal Docker DNS)
resolver 127.0.0.11 valid=10s;

# Global Log (Semua traffic akan mengalir ke stdout agar dibaca Promtail)
access_log /dev/stdout json_analytics;
error_log /dev/stderr warn;

# 1. LOGIKA MAP (Wajib di luar block server)
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

# Force HTTPS Scheme when behind proxy
map $http_x_forwarded_proto $proxy_x_forwarded_proto {
  default $http_x_forwarded_proto;
  ''      $scheme;
}

# --- SERVER BLOCKS ---

server {
    listen 80 default_server;
    server_name _;
    return 444; # Drop requests with unknown host header
}

server {
    listen 80;
    server_name load_balancer;
    location /stub_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;   
        allow 172.16.0.0/12;
        allow 10.0.0.0/8; 
        allow 192.168.0.0/16;
        deny all;          
    }
}



# HMR server block is generated conditionally from templates/hmr.conf
